video:
  resize_width: 1280
  frame_stride: 1
processing:
  roi:
    x: 800
    y: 200
    width: 400
    height: 500
  clahe_clip_limit: 3.0
  clahe_tile_grid_size: 8
  blur_kernel: 3
  adaptive_threshold_block_size: 35
  adaptive_threshold_C: -5

detector:
  hsv_lower: [0, 0, 200]
  hsv_upper: [180, 60, 255]
  min_area: 15
  max_area: 5000
  dilation_iterations: 1

metrics:
  decay_halflife_seconds: 2.0
  frame_rate_override: null
  intensity_to_damage_scale: 0.05

output:
  save_debug_frames: false
  debug_dir: "reports/debug"
  csv_path: "reports/sample-run.csv"
  json_path: "reports/sample-run.json"
